openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /chat/completion:
    post:
      operationId: chat_completion_chat_completion_post
      requestBody:
        content:
          application/json:
            example:
              text_list:
                messages:
                - role: user
                  content: Not working
                - role: system
                  content: Try again?
            schema:
              $ref: '#/components/schemas/ChatCompletionReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Chat Completion
components:
  schemas:
    ChatCompletionReq:
      example:
        top_p: 1.4658129805029452
        stop: Stop
        text_list:
          messages:
          - role: system
            generated: generated
            content: ""
          - role: system
            generated: generated
            content: ""
        max_tokens: 0
        temperature: 6.027456183070403
        model: Model
        id: 5ffa5d5b-5faa-4f6b-bf43-5dcecf932269
        req_time: 2000-01-23T04:56:07.000+00:00
      properties:
        max_tokens:
          $ref: '#/components/schemas/Max_Tokens'
        temperature:
          default: 0.2
          title: Temperature
          type: number
        top_p:
          default: 0.95
          title: Top P
          type: number
        stop:
          $ref: '#/components/schemas/Stop'
        model:
          $ref: '#/components/schemas/Model'
        id:
          default: 5ffa5d5b-5faa-4f6b-bf43-5dcecf932269
          title: Id
          type: string
        req_time:
          default: 2024-02-18T21:17:20.767221
          format: date-time
          title: Req Time
          type: string
        text_list:
          $ref: '#/components/schemas/ChatTextList'
      required:
      - text_list
      title: ChatCompletionReq
    ChatText:
      description: Represents a single message in a conversation.
      example:
        role: system
        generated: generated
        content: ""
      properties:
        role:
          default: system
          title: Role
          type: string
        content: {}
        generated:
          title: Generated
          type: string
      required:
      - content
      title: ChatText
    ChatTextList:
      description: Represents a collection of messages in a conversation.
      example:
        messages:
        - role: system
          generated: generated
          content: ""
        - role: system
          generated: generated
          content: ""
      properties:
        messages:
          default: []
          items:
            $ref: '#/components/schemas/ChatText'
          type: array
      title: ChatTextList
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    Max_Tokens:
      anyOf:
      - type: integer
      - nullable: true
      default: 1000
      title: Max Tokens
    Stop:
      anyOf:
      - type: string
      - items:
          type: string
      - nullable: true
      default: []
      title: Stop
    Model:
      anyOf:
      - type: string
      - nullable: true
      title: Model
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer

